all:
  children:
    kubernetes_masters:
      hosts:
        k8s-master:
          ansible_host: <YOUR_K8S_MASTER_IP>
          ansible_user: <YOUR_K8S_USER>
          ansible_ssh_private_key_file: ~/.ssh/k8s-cluster-key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python3
      vars:
        kubernetes_role: master
        zabbix_namespace: zabbix-monitoring
        kubectl_path: /usr/local/bin/kubectl
        
    monitoring:
      children:
        kubernetes_masters:
      vars:
        # Zabbix 7.0 LTS Configuration
        zabbix_version: "7.0-ubuntu-latest"
        zabbix_server_image: "zabbix/zabbix-server-pgsql:{{ zabbix_version }}"
        zabbix_web_image: "zabbix/zabbix-web-nginx-pgsql:{{ zabbix_version }}"
        zabbix_proxy_image: "zabbix/zabbix-proxy-mysql:{{ zabbix_version }}"
        
        # Database Configuration
        postgres_version: "15-alpine"
        postgres_image: "postgres:{{ postgres_version }}"
        postgres_database: "zabbix"
        postgres_user: "zabbix"
        postgres_password: "<YOUR_POSTGRES_PASSWORD>"
        postgres_root_password: "<YOUR_POSTGRES_ROOT_PASSWORD>"
        
        # Storage Configuration
        storage_class: "longhorn"
        postgres_storage_size: "20Gi"
        zabbix_server_storage_size: "10Gi"
        
        # Network Configuration
        zabbix_web_nodeport_http: 30080
        zabbix_web_nodeport_https: 30443
        zabbix_server_port: 10051
        
        # Corporate Environment Settings
        zabbix_server_name: "Zabbix 7.0 LTS Corporate Monitoring"
        php_timezone: "America/Sao_Paulo"
        
        # Performance Tuning for Corporate (300+ hosts)
        zabbix_cache_size: "256M"
        zabbix_history_cache_size: "512M"
        zabbix_trend_cache_size: "256M"
        zabbix_value_cache_size: "512M"
        zabbix_start_pollers: "20"
        zabbix_start_trappers: "10"
        zabbix_start_pingers: "5"
        zabbix_start_discoverers: "3"
        zabbix_start_http_pollers: "5"
        
        # Security Configuration
        enable_https: true
        enable_ingress: false
        ingress_host: "<your-zabbix-domain.local>"
